version: "2"

services:
  db:
    image: mysql:8.0.26
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: blog_gotit
      MYSQL_USER: interview
      MYSQL_PASSWORD: interview
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 33067:3306

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        "app:create_app()"
    ports:
      - 8000:8000
    volumes:
      - .:/blog-gotit
    links:
      - db
