"""empty message

Revision ID: 8a1f9364b3bb
Revises: c0a0ae4e32c7
Create Date: 2021-10-09 22:04:01.855660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1f9364b3bb'
down_revision = 'c0a0ae4e32c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_auth', sa.Column('occupation', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_auth', 'occupation')
    # ### end Alembic commands ###
