"""empty message

Revision ID: a0573658acfa
Revises: f97cce83b5a0
Create Date: 2021-10-08 13:36:18.785007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0573658acfa'
down_revision = 'f97cce83b5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'created_at')
    # ### end Alembic commands ###
