"""empty message

Revision ID: c0a0ae4e32c7
Revises: a0573658acfa
Create Date: 2021-10-09 13:36:15.494173

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c0a0ae4e32c7'
down_revision = 'a0573658acfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gg_user_id', sa.String(length=128), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_auth_email'), 'google_auth', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_auth_email'), table_name='google_auth')
    op.drop_table('google_auth')
    # ### end Alembic commands ###
