"""empty message

Revision ID: eba0948274ef
Revises: 
Create Date: 2021-10-08 11:35:35.749880

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'eba0948274ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facebook_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fb_user_id', sa.String(length=128), nullable=False),
    sa.Column('email', sqlalchemy_utils.types.email.EmailType(length=255), nullable=False),
    sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facebook_auth_email'), 'facebook_auth', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facebook_auth_email'), table_name='facebook_auth')
    op.drop_table('facebook_auth')
    op.drop_table('user')
    # ### end Alembic commands ###
